#################################################################
#
# render.yaml
#
# Blueprint for shared PostgreSQL deployment
#
# Overview
# - Free-tier expires every 30 days
# - <External Database URL> is for connecting to the instance with psql:
#      e.g. $ psql "postgresql://<user>:<password>@<host>/<auth_prod>" -c "CREATE DATABASE <name_db>;"
# - <Internal Database URL> value is the URl for projects that use it
#      Update Environment variables: DB_URL=...<Internal Database URL without the primary database name>/<name_db>
#
# Steps
# 1. Delete the existing (expired) postgres instance
# 2. Navigate to https://dashboard.render.com/blueprints
# 3. Run the "PostgreSQL Deployment" blueprint (it executes this script)
#    This will create the postgres instance shared by all spps that need it
# 4. Get the new connection strings:
#    <External Database URL>
#    <Internal Database URL> -- remove the primary_prod* database from the end
# 5. Create the app databases (the apps that have blueprints use postgres):
#    NOTE: !! See scripts/set-cs.sh.EXAMPLE script!!
#       psql "<external_database_url>" -c "CREATE DATABASE bookshelter_db;"
#       psql "<external_database_url>" -c "CREATE DATABASE kanban_db;"
#       psql "<external_database_url>" -c "CREATE DATABASE routinesaga_db;"
# 6. Update each app's environment: DB_URL=...<Internal Database URL>/<appname_db>
# 7. Run each app's blueprint to redeploy it
# 8. Update your reminder for the new expiration date (see the postgresql deployment details)
#
# (ref: https://render.com/docs/blueprint-spec#)
#
#################################################################

databases:
  - name: render-postgres
    plan: free
    # postgresMajorVersion: "16" # defaults to latest
    databaseName: auth_prod
    user: auth_rw
    region: oregon
