#################################################################
#
# render.yaml
#
# Blueprint for shared PostgreSQL deployment
#
# Free-tier
# - Expires every 30 days
# - Use <External Database URL> to connect with psql and create the databases:
#   $ psql "postgresql://<user>:<password>@<host>/<auth_prod>" -c "CREATE DATABASE <name_db>;"
# - Use <Internal Database URL> value for projects that use it
#   Update Environment variables: DB_URL=...<Internal Database URL>/<name_db>
#
# 1. Delete the existing (expired) postgres instance
# 2. Navigate to https://dashboard.render.com/blueprints
# 3. Run the postgres deployment blueprint
#    This will create the postgres depoyment
# 4. Create the app databases:
#    psql "<External Database URL> -c "CREATE DATABASE <name_db1>; CREATE DATABASE <name_db2>; ... "
# 5. Update each app's environment: DB_URL=...<Internal Database URL>/<name_db>
# 6. Run each app's blueprint to redeploy
#
# (ref: https://render.com/docs/blueprint-spec#)
#
#################################################################

databases:
  - name: render-postgres
    plan: free
    # postgresMajorVersion: "16" # defaults to latest
    databaseName: auth_prod
    user: auth_rw
    region: oregon

  - name: routinesaga-db
    plan: free
    databaseName: routinesaga_db
    user: saga_rw
    region: oregon

services:
  - type: web
    name: routine-saga
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install -r requirements_prod.txt
    startCommand: python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: ROUTINESAGA_DATABASE_URL
        fromDatabase:
          name: routinesaga-db
          property: connectionString