#################################################################
#
# render.yaml
#
# Blueprint for shared PostgreSQL deployment
#
# Overview
# - Free-tier expires every 30 days
# - <External Database URL> is for connecting to the instance with psql:
#      e.g. $ psql "postgresql://<user>:<password>@<host>/<auth_prod>" -c "CREATE DATABASE <name_db>;"
# - <Internal Database URL> value is the URl for projects that use it
#      Update Environment variables: DB_URL=...<Internal Database URL without the primary database name>/<name_db>
#
# Steps
# 1. Delete the existing (expired) postgres instance:
#    https://dashboard.render.com/
# 2. Navigate to the blueprints:
#    https://dashboard.render.com/blueprints
# 3. Run the "PostgreSQL Deployment" blueprint (it executes this script): Manual synch, Approve
#    This will create the postgres instance (~5m) shared by all spps that need it
# 4. Get the new connection strings:
#    <Internal Database URL> -- remove the primary_prod* database from the end
#    <External Database URL>
# 5. Create the app databases in the new instance (the apps that have Render blueprints use postgres):
#    See scripts/set-cs.sh.EXAMPLE:
#       scripts/set-cs.sh
# 6. On Render, update each app's environment and redeploy:
#    DB_URL=...<Internal Database URL>/<appname_db>
# 7. Optional: To create an app from scratch, run the app's blueprint
# 8. Update your reminder for the new expiration date (see the postgresql deployment details)
#
# (ref: https://render.com/docs/blueprint-spec#)
#
#################################################################

databases:
  - name: postgres-prod
    plan: free
    # postgresMajorVersion: "16" # defaults to latest
    databaseName: primary_prod
    user: auth_rw
    region: oregon
