#################################################################
#
# render.yaml
#
# Blueprint for shared PostgreSQL deployment
#
# Free-tier
# - Expires every 30 days
# - Use <External Database URL> to connect with psql and create the databases:
#   $ psql "postgresql://<user>:<password>@<host>/<auth_prod>" -c "CREATE DATABASE <name_db>;"
# - Use <Internal Database URL> value for projects that use it
#   Update Environment variables: DB_URL=...<Internal Database URL>/<name_db>
#
# 1. Delete the existing (expired) postgres instance
# 2. Navigate to https://dashboard.render.com/blueprints
# 3. Run the postgres deployment blueprint
#    This will create the postgres depoyment
# 4. Create the app databases:
#    psql "<External Database URL> -c "CREATE DATABASE <name_db1>; CREATE DATABASE <name_db2>; ... "
# 5. Update each app's environment: DB_URL=...<Internal Database URL>/<name_db>
# 6. Run each app's blueprint to redeploy
#
# (ref: https://render.com/docs/blueprint-spec#)
#
#################################################################

databases:
  - name: postgres
    plan: free
    # postgresMajorVersion: "16" # defaults to latest
    databaseName: primary_prod
    user: auth_rw
    region: oregon

services:
  - type: web
    name: BookShelter
    plan: free
    branch: main
    runtime: node
    buildCommand: npm run render-seed
    startCommand: npm start
    envVars:
      # Inject primary DB's connection string
      # NOTE: you must manually update the database name in each of the Web Apps
      #   to its individual name
      - key: DB_URL
        fromDatabase:
          name: render-postgres
          property: connectionString

  - type: web
    name: InYourLane
    plan: free
    branch: main
    runtime: node
    buildCommand: npm run render-seed
    startCommand: npm start
    envVars:
      # Inject primary DB's connection string
      # NOTE: you must manually update the database name in each of the Web Apps
      #   to its individual name
      - key: DB_URL
        fromDatabase:
          name: render-postgres
          property: connectionString

  - type: web
    name: routine-saga
    plan: free
    branch: main
    runtime: python
    buildCommand: pip install -r requirements_prod.txt
    startCommand: python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      # Inject primary DB's connection string
      # NOTE: you must manually update the database name in each of the Web Apps
      #   to its individual name
      - key: DB_URL
        fromDatabase:
          name: render-postgres
          property: connectionString
